import React from "react";
import Image from "next/image";
import Hero from "@/app/components/hero"

export const metadata = {
  title: "Reliability",
  description: "Generated by create next app",
};
export default function page() {
  return (
    <Hero
      imageUrl='/reliability.jpg'
      altText='reliability image'
      content="reliability Cloud Hosting"
    />
  );
}

