import React from "react";
import Image from "next/image";
import Hero from "../components/hero";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};
export default function page() {
  return <Hero imageUrl="/home.jpg" altText="home image" content="Home" />;
}
