import React from "react";
import Hero from "../components/hero";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};
export default function page() {
  return <Hero imageUrl="/home.jpg" altText="home image" content="测试自动化部署" />;
}
