
import React from "react";
import Hero from "@/app/components/hero"

export const metadata = {
  title: "Scale",
  description: "Generated by create next app",
};
export default function page() {
  return (
    <Hero
      imageUrl='/scale.jpg'
      altText='scale image'
      content="scale Cloud Hosting"
    />
  );
}
