import React from "react";
import Image from "next/image";
import Hero from "@/app/components/hero"

export const metadata = {
  title: "Performance",
  description: "Generated by create next app",
};
export default function page() {
  return (
    <Hero
      imageUrl='/performance.jpg'
      altText='performance image'
      content="performance Cloud Hosting"
    />
  );
}

